Go (ур. 2) - Решение домашнего задания к уроку №5
GoncharSY/geekbrains pull request #14
Opened 2022-09-07 14:26 UTC by GoncharSY

1. Напишите программу, которая запускает **𝑛** потоков и дожидается завершения их всех.
2. Реализуйте функцию для разблокировки мьютекса с помощью `defer`.
3. Протестируйте производительность операций чтения и записи на множестве действительных чисел, безопасность которого обеспечивается `sync.Mutex` и `sync.RWMutex` для разных вариантов использования:

    - 10% запись, 90% чтение;
    - 50% запись, 50% чтение;
    - 90% запись, 10% чтение.

2022-09-07 14:31 UTC, GoncharSY commented
Первое задание оказалось совсем несложным. Я добавил сообщения о запуске всех горутин и об их завершении:

![waitgroup](https://user-images.githubusercontent.com/47101945/188904131-c7cf7237-761e-4f41-a597-0260f4904f18.PNG)

`sync.WaitGroup` - классная штука, мне нравится...

2022-09-07 17:23 UTC, GoncharSY commented
Второе задание еще проще первого. Я решил не мудрить:

![image](https://user-images.githubusercontent.com/47101945/188940881-90008234-febb-440e-a65d-72e25935b785.png)

2022-09-07 20:33 UTC, GoncharSY commented
Третье задание снова описано не совсем ясно. Поэтому выполнял, как понял. В тесте я запускаю прогоны кейсов в последовательном и параллельном режимах:

![image](https://user-images.githubusercontent.com/47101945/188970988-9400818d-b874-4f3c-a39b-4fadb722a83d.png)

В последовательном прогоне видно, что `RWMutex` работает медленней, нежели `Mutex`. Особенно с увеличением доли записи это заметно. Однако при параллельных тестах значения меняются, и не понятно почему операции записи занимают меньше времени с `RWMutex`.

2022-09-11 13:12 UTC, rowdyroad requested changes

2022-09-11 13:12 UTC, rowdyroad commented on go-level-2/lesson-05/README.md
> +3. Протестируйте производительность операций чтения и записи на множестве действительных чисел, безопасность которого обеспечивается `sync.Mutex` и `sync.RWMutex` для разных вариантов использования:
Имеется ввиду что например 10 горутин пишет, 90 читает в одно и тоже время, в твоем коде идет одновременно читка и запись

2022-09-15 19:02 UTC, merged